### ISSUE TITLE
[Bug] `unknown word` error with tailwindcss

### ISSUE THREAD

**Issue by JohnPangalos** [storybookjs/addon-postcss#18]
### Error when trying to use tailwind with postcss plugin

Getting `unknown word` error when trying to use tailwindcss in post css.
```
ERROR in ./src/stories/page.css (./node_modules/css-loader/dist/cjs.js!./node_modules/@storybook/addon-postcss/node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src??ref--12-2!./src/stories/page.css)
Module build failed (from ./node_modules/@storybook/addon-postcss/node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) /Users/johnpangalos/repos/vite-project/src/stories/page.css Unknown word

> 1 | var api = require("!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
    | ^
  2 |             var content = require("!!../../node_modules/css-loader/dist/cjs.js??ref--12-1!../../node_modules/postcss-loader/src/index.js??ref--12-2!./page.css");
  3 |
```
### Steps to reproduce the behavior

1. Setup a new react project with storybook
2. Add post css addon 
3. Add tailwind according to [postcss guide](https://tailwindcss.com/docs/installation#installing-tailwind-css-as-a-post-css-plugin)
4. Move to postcss version 8 as described in the readme.
4. Import [tailwind directive](https://tailwindcss.com/docs/functions-and-directives#tailwind) into a file
5. Run storybook

### Expected behavior

Storybook would run with a postcss generated tailwindcss file

### Screenshots and/or logs

Repro Repo: https://github.com/JohnPangalos/storybook-tailwind

### Environment

 - OS: MacOS (aarch64)
 - Node.js version: 15.11.0
 - NPM version: 7.6.0

**Comment by mercs600** [comment]
the same issue here, 

.storybook/main.js
```js
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss')
        }
      }
    },
    '@storybook/addon-links',
    '@storybook/preset-typescript',
    '@storybook/addon-controls'
  ],
  ```

postcss.config.js
```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  }
}

```

some important deps: 
```json
    "@storybook/addon-actions": "^6.1.21",
    "@storybook/addon-controls": "^6.1.21",
    "@storybook/addon-docs": "^6.1.21",
    "@storybook/addon-essentials": "^6.1.21",
    "@storybook/addon-links": "^6.1.21",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/preset-typescript": "^3.0.0",
    "@storybook/vue": "^6.1.21",
 "autoprefixer": "^10.2.5",
"postcss": "^8.2.8",
    "postcss-loader": "^4.2.0",
    "tailwindcss": "^2.0.4",
```

**Comment by davidzzheng** [comment]
This issue is due to the version of storybook that you're using. According to #14 , this add-on requires the next version (>= `6.2`) of storybook. I have a working template that you can use as a reference: https://github.com/davidzzheng/tailwind-storybook

**Comment by JohnPangalos** [comment]
Oh thanks @davidzzheng would it be possible to add this to the readme? I feel like it might save people some time.

**Comment by ashnamuh** [comment]
Hello, i have a similar issue. I have to use `css-loader` and `style-loader` with `@storybook/addon-postcss` and `tailwindcss`. So, i added configurations for that. like the below codes

```js
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-essentials",
    {
      name: "@storybook/addon-postcss",
      options: {
        postcssLoaderOptions: {
          implementation: require("postcss"),
        },
      },
    },
  ],
  core: {
    builder: "webpack5",
  },
  webpackFinal: (config) => {
    config.module.rules.push({
      test: /\.s?css$/,
      use: [
        'style-loader',
        {
          loader: 'css-loader',
          options: {
            modules: {
              localIdentName: '[local]',
            },
          },
        },
        {
          loader: 'postcss-loader',
          options: {
            implementation: require('postcss')
          }
        },
      ],
    })

    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
        },
      },
    };
  },
};

```

And `Unknown word` error occured. I've create sample repository base on **davidzzheng/tailwind-storybook** and tried again. That also doesn't work as what i expected. 

sample: https://github.com/ashnamuh/tailwind-storybook

Is there any idea to resolve this issue??

**Comment by JohnPangalos** [comment]
@davidzzheng I can confirm that changing to version 6.2 fixed my issue, closing! Thanks for the help.

**Comment by sshquack** [comment]
This error is back on CRA 5 + SB 6.4 + addon-postcss 2.0 See https://github.com/storybookjs/addon-postcss/issues/33

**Comment by tomtomau** [comment]
None of the solutions worked for me on SB 6.5, and the requirement to add `import '!style-loader!css-loader!postcss-loader!` infront of every import was pretty gross imo.

What did work for me was removing all existing CSS rules from the webpack config and then adding in my own. I didn't add the addon-postcss as a plugin either, that wouldn't work for me:
```
  webpackFinal: (config) => {
    const filterOutCssRule = (rule) => {
      const patterns = [
        /\.css$/i,
        /\.css$/,
      ];

      return patterns.every((p) => {
        return rule.test.toString() !== p.toString();
      });
    };

    config.module = {
      ...(config.module || {}),
      rules: [
        ...(config.module.rules.filter(filterOutCssRule) || []),
        {
          test: /\.css$/i,
          use: [
            'style-loader',
            'css-loader',
            'postcss-loader',
          ],
        },
      ],
    };

    return config;
  },
  ```
