### ISSUE TITLE
Don't depend directly on postcss?

### ISSUE THREAD

**Issue by phated** [storybookjs/addon-postcss#6]
Currently, this module is shipping with a direct dependency on `postcss@^7.0.35`, but allows the implementation to be overridden.

Should we just have a peerDep on `postcss` instead? That way consumers can just install the version of the tool they want/need.

**Comment by shilman** [comment]
I thought this was already the plan in your original PR? I approve making it a `peerDep`/`devDep` 👍

**Comment by shilman** [comment]
Kind of a duplicate to #4?

**Comment by phated** [comment]
The decision was to depend directly on PostCSS and the loaders to make this easy to use. Since this is versioned separately from storybook itself, we can just keep those dependencies updated as we see fit.

I'll also be removing the webpack peerDep, since that is managed by storybook core.
